# This Rakefile just ensures that the necessary framework symlinks are in place
# when installed as a gem, as RubyGems doesn't play nice with symlinks.

task :prepare do
  Dir.glob('*.framework').each do |fw|
    p fw
    Dir.chdir(fw) do
      basename = File.basename(fw, '*.framework')
      version = Dir.glob('Versions/*').sort.last

      File.symlink(version,                        'Versions/Current')
      File.symlink("Versions/Current/#{basename}", "#{basename}")
      File.symlink("Versions/Current/Resources",   "Resources")
      File.symlink("Versions/Current/Modules",     "Modules")
    end
  end
end

task default: :prepare
